from abc import ABC, abstractmethod
from typing import Optional

class Browser(ABC):
    @abstractmethod
    async def open_tab(self, agent_id: str) -> str: ...

    @abstractmethod
    async def close_tab(self, agent_id: str) -> str: ...

    @abstractmethod
    async def navigate(self, agent_id: str, url: str) -> str: ...

    @abstractmethod
    async def execute_js(self, agent_id: str, script: str) -> str: ...

    @abstractmethod
    async def get_console_logs(self, agent_id: str) -> str: ...

    @abstractmethod
    async def get_accessibility_tree(self, agent_id: str) -> str: ...

    @abstractmethod
    async def interact_click(self, agent_id: str, selector_or_id: str) -> str: ...

    @abstractmethod
    async def interact_type(self, agent_id: str, selector_or_id: str, text: str) -> str: ...

    @abstractmethod
    async def search_duckduckgo_serp(self, agent_id: str, query: str) -> str: ...

    @abstractmethod
    async def take_screenshot(self, agent_id: str) -> str: ...

    @abstractmethod
    async def capture_screenshot_to_file(self, agent_id: str, file_path: str) -> str: ...

    @abstractmethod
    async def save_as_pdf(self, agent_id: str, file_path: Optional[str] = None) -> str: ...

    @abstractmethod
    async def wait_for_selector(self, agent_id: str, selector: str, timeout_ms: int = 30000) -> str: ...

    @abstractmethod
    async def wait_for_load_state(self, agent_id: str, state: str = "networkidle") -> str: ...

    @abstractmethod
    async def wait(self, agent_id: str, time_ms: int) -> str: ...

    @abstractmethod
    async def interact_scroll(self, agent_id: str, direction: str, amount: int) -> str: ...

    @abstractmethod
    async def select_dropdown_option(self, agent_id: str, selector: str, value: str) -> str: ...

    @abstractmethod
    async def close(self) -> None: ...
